### ISSUE TITLE
Pelican or Jekyll for website?

### ISSUE THREAD

**Issue by pauleveritt** [Jycraft/jycraft.github.io#1]
I'm working my way through learning Pelican. I will probably have to fork an existing theme to get what we ultimately want.

Before I do so, I want to confirm something with @Macuyiko on this. If we go with Jekyll and don't use any custom plugins, we can change the content without having to run it through a static generator. Meaning, people could edit the website via the editor pages on github.com.

But if we use Pelican (or a custom Jekyll), when someone makes a change, they will have to run the Pelican build scripts locally before pushing the results. There are some ways around this (have a commit hook that calls a process we leave running somewhere, or have Travis build it for us then push it to the repo.)

Unless I hear otherwise, I will stick with local Pelican and we'll sort out improvements later.

**Comment by Macuyiko** [comment]
Both are okay, for Pelican, we could follow the following strategy:

1) set up a new repo to host the Pelican installation / configuration
2) configure Pelican to write the output files to a directory outside the Pelican install path
3) this output directory is linked with the actual site repo (jycraft,github.io) and can be pushed

This still means people'll need to push after recompiling the site, but at least then the config and themes are also managed by a repo... Later on, we can hook it up to a process.

**Comment by pauleveritt** [comment]
Pelican has some ways to do all that using one repo. If we want to use Travis, though, to eliminate the generation part, then I believe we’ll have to do the split that you mention. I’ll stick with what I have.

Also, I’m not going to overdo it at the moment on a great site. It will be a home page, some other pages, and a blog-style set of articles.
