### ISSUE TITLE
Setup for dev

### ISSUE THREAD

**Issue by AngelMunoz** [Jycraft/jycraft.github.io#2]
Hey I would like to contribute here and I'm trying to set this up with pelican, but no success mimicking what's on the live site, any help (it doesn't have to be pelican) on how to set up the dev environment for this repo?

**Comment by pauleveritt** [comment]
Thanks Angel for bringing this up. I’ll look at it later today. Also, if I make some Europe-friendly time slots this weekend to be online in IRC/Gitter, do you think you would be interested in an online Jycraft meeting?

—Paul

**Comment by AngelMunoz** [comment]
Yes, I am intrested, but I don't know if I'm going to be able to get in time, (UTC/GMT-7 here) but I am intrested in cooperating

**Comment by pauleveritt** [comment]
I’ve somewhat convinced myself that what I really want is to author in Sphinx, with rich interlinking. Which means ABlog. But ABlog doesn’t seem to have a facility for customizing the theme…I think it just pulls in Alabaster.

I might be looking at this wrong, though…perhaps it just lets Sphinx do the selection of the theme.

Angel, two questions for you:
- How do you feel about the Pelican vs. Sphinx/ABlog point?
- Would you be interested in investigating how to get a custom theme in Sphinx/ABlog?

—Paul

**Comment by AngelMunoz** [comment]
I'm not familiar with any [pelican/ sphynx] to be sincere, but if you are already familiar with Sphynx/Ablog I would rather go with those instead Pelican.

Doing some quick research you can change the ablog theme in the config.py rules. check a screenshot of the said thing right here using **sphinx_rtd_theme** instead of **alabaster**:
![term](https://cloud.githubusercontent.com/assets/8684875/10707130/40db7cce-79ab-11e5-9186-6d5db1912f6d.PNG)
![ablogtheme](https://cloud.githubusercontent.com/assets/8684875/10707059/b3df47b0-79aa-11e5-88bd-bcf747191bfb.PNG)
so changing the theme wouldn't be a problem.
But I don't think the custom theme would be that easly, since you have to write a complete python package, to use it, we could fork a theme and start developing it for our own needs but I'm not sure how quick or efective would that be.

But in the end, I'm here to contribute If we need to develop our own theme I'm all ears :+1:

**Comment by pauleveritt** [comment]
Sorry for not replying, yesterday was my wife’s birthday.

I think you’re right that we can now proceed with ABlog instead of Pelican. Let’s do some trials with some of the key features we’ll need. In order:
- Pushing to GitHub
- (Later) Disqus integration

I think we’ll need a custom home page. I don’t know if Sphinx has a facility for that. If not, we can do something like this:
- For an existing theme
- Gradually make some small changes, for example, conditionals for the home page

—Paul

**Comment by AngelMunoz** [comment]
Well, then is decided then, I'll start with something made with Ablog, and try to see if we can get a nice template, after that I'll go for the custom layouts and then I'll proceed with look and feel, but those are for separate issues thank you
